export const FILTRAR = 'FILTRAR'
export const ORDENAR = 'ORDENAR'
export const AGREGAR_PELIS = 'AGREGAR_PELIS'
export const AGREGAR_PELI = 'AGREGAR_PELI'
export const ELIMINAR_PELI = 'ELIMINAR_PELI'
export const ANTERIOR = 'ANTERIOR'
export const SIGUIENTE = 'SIGUIENTE'
export const HAY_BUSQUEDA = 'HAY_BUSQUEDA'