export const APIKEY = ''
export const URLBASE = 'https://www.omdbapi.com/?apikey='
export const ID = '&i='
export const TITULO = '&t='
export const BUSQUEDA = '&s='
export const PAGINA = '&page='
export const ERROR_PETICION = 'Hubo un error al realizar la petición'
